site_name: "Docker Commands Reference"
theme:
  name: "material"

nav:
  - Home: index.md
  - Docker Basics: basics.md
  - Docker Containers: containers.md
  - Docker Images: images.md
  - Docker Networking: networking.md
